name: Update AoC Badges 2023
on:
  workflow_dispatch:

  schedule:
    - cron: "50 4 1-25 12 *" # from December 1st to 26th every day at 4:50 UTC (23:50 EST)

  # push: # (disabled) run on push, be careful with this setting
  #       # as the workflow should only be triggered at a rate lower than
  #       # 4 times a hour to keep traffic on aoc site low

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.

    steps:
      - uses: actions/checkout@v2

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USER_ID }} # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_COOKIE }}
          year: 2023
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/Advent%20of%20Code%202023-)[0-9]+(?=/25.*)'

          # Optional inputs:
          #
          # year: 2021                                                                                     # The year for which stats should be retrieved
          # leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          # file: 'README.md'                                                                              # The file that contains the badges
          # dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20ðŸ“…-)[0-9]+(?=-blue)'                    # Regular expression that finds the content of the day badge in your file.
          # starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20â­-)[0-9]+(?=-yellow)'              # Regular expression that finds the content of the stars badge in your file.
          # daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Advent of Code badges
          file_pattern: README.md
